# Generated by Django 3.2.7 on 2021-09-26 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telemedicine', '0003_auto_20210926_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='current_medications',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
